reporte_mensual_proyecto/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('inicio.urls', namespace='inicio')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^sisrep/', include('registro.urls', namespace='registro')),
    url(r'^safet/', include('safet.urls', namespace='safet')),
    url(r'^bitacora/', include('bitacora.urls', namespace='bitacora')),
    url(r'^admin/', include(admin.site.urls)),
]

safet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from safet import views
from safet.views import *
import safet.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^carga_inicial$', login_required(IndexCargaInicial.as_view()), name='inicio_carga_inicial'),
    url(r'^reporte_avances$', login_required(IndexReporte_avances.as_view()), name='inicio_reporte_avances'),
    url(r'^reporte_actividades$', login_required(IndexReporte_actividades.as_view()), name='inicio_reporte_actividades'),
    ##### Crud de los proyectos poa ######
    url(r'^consultar_proyecto$', login_required(views.Consultar_proyecto.as_view()), name='consultar_proyecto'),
    url(r'^registrar_proyecto$', login_required(views.Registrar_proyecto.as_view()), name='registrar_proyecto'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', login_required(views.Editar_proyecto.as_view()), name='editar_proyecto'),
    url(r'^borrar_proyecto/(?P<pk>\d+)$', login_required(views.Borrar_proyecto.as_view()), name='borrar_proyecto'),
    ##### Crud de las acciones específicas ######
    url(r'^consultar_accion$', login_required(views.Consultar_accion.as_view()), name='consultar_accion'),
    url(r'^registrar_accion$', login_required(views.Registrar_accion.as_view()), name='registrar_accion'),
    url(r'^editar_accion/(?P<pk>\d+)$', login_required(views.Editar_accion.as_view()), name='editar_accion'),
    url(r'^borrar_accion/(?P<pk>\d+)$', login_required(views.Borrar_accion.as_view()), name='borrar_accion'),
    ##### Crud de los Reportes de avances para los analistas ######
    url(r'^consultar_reporte_avances$', login_required(views.Consultar_reporte_avances.as_view()), name='consultar_reporte_avances'),
    url(r'^registrar_reporte_avances$', login_required(views.Registrar_reporte_avances.as_view()), name='registrar_reporte_avances'),
    url(r'^editar_reporte_avances/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances.as_view()), name='editar_reporte_avances'),
    url(r'^detallar_reporte_avances/(?P<pk>\d+)$', login_required(views.Detallar_reporte_avances.as_view()), name='detallar_reporte_avances'),
    url(r'^registrar_reporte_avances_software$', login_required(views.Registrar_reporte_avances_software.as_view()), name='registrar_reporte_avances_software'),
    url(r'^registrar_reporte_avances_cur_lin$', login_required(views.Registrar_reporte_avances_cur_lin.as_view()), name='registrar_reporte_avances_cur_lin'),
    url(r'^registrar_reporte_avances_jornada$', login_required(views.Registrar_reporte_avances_jornada.as_view()), name='registrar_reporte_avances_jornada'),
    url(r'^registrar_reporte_avances_publicacion$', login_required(views.Registrar_reporte_avances_publicacion.as_view()), name='registrar_reporte_avances_publicacion'),
    url(r'^borrar_reporte_avances/(?P<pk>\d+)$', login_required(views.Borrar_reporte_avances.as_view()), name='borrar_reporte_avances'),
    ##### Crud de los Reportes de Avances para los CV ######
    url(r'^consultar_reporte_avances_cv$', login_required(views.Consultar_reporte_avances_cv.as_view()), name='consultar_reporte_avances_cv'),
    url(r'^editar_reporte_avances_cv/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances_cv.as_view()), name='editar_reporte_avances_cv'),
    ##### Reportes porcentuales #####
    url(r'^buscar/$', login_required(views.Buscar.as_view()), name='consultar_reporte_avances_cv_por'),
    url(r'^busqueda/$', login_required(views.busqueda), name='busqueda'),
)

safet/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from safet.models import ProyectoPoa, AccionEspecifica, ReporteAvances
from bitacora.models import Bitacora
from forms import ProyectoPoaForm, AccionEspecificaForm, ReporteAvancesForm, ReporteAvancesSoftwareForm, ReporteAvancesCursoLineaForm, ReporteAvancesJornadaForm, ReporteAvancesCVForm, ReporteAvancesPublicacionForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import *
from django.core.urlresolvers import *
from django.db.models import Count
from django.template import RequestContext
from django.contrib.auth.models import User
from django.shortcuts import redirect
from datetime import datetime
#is_active = Cara visible
#is_staff = Supervisor
#is_superuser = Analista


class IndexCargaInicial(TemplateView):
    """
    Plantilla de inicio del módulo de carga inicial
    """
    template_name = "safet/inicio_carga_inicial.html"


class IndexReporte_avances(TemplateView):
    """
    Plantilla de inicio del módulo de reportes de avances.
    """
    template_name = "safet/inicio_reporte_avances.html"


class IndexReporte_actividades(TemplateView):
    """
    Plantilla de inicio del módulo de reportes de actividades.
    """
    template_name = "safet/inicio_reporte_actividades.html"


#####################################
##### Crud de los proyectos poa #####
#####################################

class Consultar_proyecto(ListView):
    """
    Clase que permite consultar la lista de proyectos poa.
    """
    model = ProyectoPoa

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario es admin para ver la lista de objetos.
        """
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            if (self.get_paginate_by(self.object_list) is not None
                    and hasattr(self.object_list, 'exists')):
                is_empty = not self.object_list.exists()
            else:
                is_empty = len(self.object_list) == 0
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.")
                        % {'class_name': self.__class__.__name__})
        context = self.get_context_data()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            messages_alert = ['No tiene permisos para listar los proyectos poa']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Registrar_proyecto(SuccessMessageMixin,CreateView):
    """
    Clase que permite registrar un proyecto poa.
    """
    model = ProyectoPoa
    form_class = ProyectoPoaForm
    success_url = reverse_lazy('safet:consultar_proyecto')
    success_message = "Se registro el proyecto poa con éxito"

    def get(self, request, *args, **kwargs):
        """
        Méroto que valida si el usuario autenticado es admin
        para poder registrar un proyecto.
        """
        self.object = None
        if request.user.is_superuser:
            return super(Registrar_proyecto, self).get(request, *args, **kwargs)
        else:
            messages_alert = ['No tiene permisos para registrar un proyecto poa']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Editar_proyecto(SuccessMessageMixin,UpdateView):
    """
    Clase que permite editar la data guardada de un proyecto poa.
    """
    model = ProyectoPoa
    form_class = ProyectoPoaForm
    success_url = reverse_lazy('safet:consultar_proyecto')
    success_message = "Se actualizo el proyecto poa con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta editar el proyecto no es admin.
        """
        self.object = self.get_object()
        if request.user.is_superuser:
            return super(Editar_proyecto, self).get(request, *args, **kwargs)
        else:
            if str(self.object) == str(self.request.user):
                return super(Editar_proyecto, self).get(request, *args, **kwargs)
            else:
                messages_alert = ['No tiene permisos para editar el proyecto poa']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Borrar_proyecto(SuccessMessageMixin,DeleteView):
    """
    Clase que permite borrar un proyecto poa.
    """
    model = ProyectoPoa
    success_url = reverse_lazy('safet:consultar_proyecto')
    success_message = "Se elimino el proyecto poa con éxito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_proyecto, self).delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta borrar el proyecto no es admin.
        """
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        self.object = self.get_object()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            if str(self.object) == str(self.request.user):
                return self.render_to_response(context)
            else:
                messages_alert = ['No tiene permisos para borrar el proyecto poa']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))

#############################################
##### Crud de las acciones específicas  #####
#############################################

class Consultar_accion(ListView):
    """
    Clase que permite consultar la lista de acciones específicas.
    """
    model = AccionEspecifica

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario es admin para ver la lista de objetos.
        """
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            if (self.get_paginate_by(self.object_list) is not None
                    and hasattr(self.object_list, 'exists')):
                is_empty = not self.object_list.exists()
            else:
                is_empty = len(self.object_list) == 0
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.")
                        % {'class_name': self.__class__.__name__})
        context = self.get_context_data()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            messages_alert = ['No tiene permisos para listar las acciones específicas']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Registrar_accion(SuccessMessageMixin,CreateView):
    """
    Clase que permite registrar una acción específica.
    """
    model = AccionEspecifica
    form_class = AccionEspecificaForm
    success_url = reverse_lazy('safet:consultar_accion')
    success_message = "Se registro la acción específica con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario autenticado es admin
        para poder registrar una acción específica.
        """
        self.object = None
        if request.user.is_superuser:
            return super(Registrar_accion, self).get(request, *args, **kwargs)
        else:
            messages_alert = ['No tiene permisos para registrar una acción específica']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Editar_accion(SuccessMessageMixin,UpdateView):
    """
    Clase que permite editar la data guardada de una acción específica.
    """
    model = AccionEspecifica
    form_class = AccionEspecificaForm
    success_url = reverse_lazy('safet:consultar_accion')
    success_message = "Se actualizo la acción específica con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta editar la Acción Específica no es admin.
        """
        self.object = self.get_object()
        if request.user.is_superuser:
            return super(Editar_accion, self).get(request, *args, **kwargs)
        else:
            if str(self.object) == str(self.request.user):
                return super(Editar_accion, self).get(request, *args, **kwargs)
            else:
                messages_alert = ['No tiene permisos para editar la acción específica']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Borrar_accion(SuccessMessageMixin,DeleteView):
    """
    Clase que permite borrar una acción específica.
    """
    model = AccionEspecifica
    success_url = reverse_lazy('safet:consultar_accion')
    success_message = "Se elimino la acción específica con éxito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_accion, self).delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario

safet/templates/safet/accionespecifica_confirm_delete.html
{% extends "base/base.html" %}
{% block titulo %}Borrar acción específica{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:consultar_accion' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Borrar acción específica</h1>
<form method="post">{% csrf_token %}
  ¿Estás seguro que quieres eliminar la acción específica: <b>{{ object.nombre_accion }}</b>?
  <br />
  <br />
  <button class="btn btn-danger" type="submit">BORRAR</button>
</form>
{% endblock %}

safet/templates/safet/accionespecifica_form.html
{% extends "base/base.html" %}
{% block titulo %}Registrar acción específica{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:consultar_accion' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Registrar acción específica</h1>
<br />
<div class="row">
  <div class="col-sm-6">
    <form method="post">{% csrf_token %}
      <div class="">
        <i class="fa fa-file-text-o color-blue-system"></i>
        <b>{{ form.nombre_accion.label }}</b>
        <br />
        {{ form.nombre_accion }}
        {% if form.nombre_accion.errors %}
          <p>{{ form.nombre_accion.errors}}</p>
        {% endif %}
      </div>
      <button class="btn btn-success" type="submit">REGISTRAR</button>
    </form>
  </div>
  <div class="col-sm-6"></div>
</div>
{% endblock %}

safet/templates/safet/accionespecifica_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de acciones específicas{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:inicio_carga_inicial' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de acciones específicas</h1>
<br />
<a href="{% url 'safet:registrar_accion' %}">
  <button class="btn btn-success">REGISTRAR</button>
</a>
<br />
<br />
<table border="1px" id="example" class="display">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th>Nombre de la acción específica</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td>{{ x.nombre_accion }}</td>
    <td class="text-center td_botonera_tabla">
      <div class="row">
        <div class="col-sm-12">
          <a href="{% url 'safet:editar_accion' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href="{% url 'safet:borrar_accion' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
      </div>
    </td>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

safet/templates/safet/inicio_carga_inicial.html
{% extends "base/base.html" %}
{% block titulo %}Carga inicial{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'inicio:index' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Carga inicial</h1>
<br />
{% if request.user.is_superuser and request.user.is_staff and request.user.is_active %}
  <div class="row">
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'safet:consultar_proyecto' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Proyectos poa
          </div>
        </a>
      </div>
      <div class="glyphicon-white">
        <a href="{% url 'registro:consultar_cargo' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Cargos
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'safet:consultar_accion' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Acciones específicas
          </div>
        </a>
      </div>
      <div class="glyphicon-white">
        <a href="{% url 'registro:consultar_proyecto' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Productos
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'registro:consultar_cara_visible' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Trabajadores
          </div>
        </a>
      </div>
      <br>
      <div class="glyphicon-white">
        <a href="{% url 'registro:consultar_director' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-list glyphicon-icon"></i>
            Directores
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-2">
    </div>
  </div>
  <h2>Registrar plan de actividades</h2>
  <br>
  <div class="row">
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'safet:registrar_reporte_avances' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-file glyphicon-icon"></i>
            Genérico
          </div>
        </a>
      </div>
      <br>
      <div class="glyphicon-white">
        <a href="{% url 'safet:registrar_reporte_avances_software' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-file glyphicon-icon"></i>
            Software
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'safet:registrar_reporte_avances_cur_lin' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-file glyphicon-icon"></i>
            Curso en Línea
          </div>
        </a>
      </div>
      <div class="glyphicon-white">
        <a href="{% url 'safet:registrar_reporte_avances_jornada' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-file glyphicon-icon"></i>
            Jornada
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="glyphicon-white">
        <a href="{% url 'safet:registrar_reporte_avances_publicacion' %}" class="enlace_boton_panel">
          <div align="center">
            <i class="glyphicon glyphicon-file glyphicon-icon"></i>
            Publicación
          </div>
        </a>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

safet/templates/safet/proyectopoa_confirm_delete.html
{% extends "base/base.html" %}
{% block titulo %}Borrar proyecto poa{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:consultar_proyecto' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Borrar proyecto poa</h1>
<form method="post">{% csrf_token %}
  ¿Estás seguro que quieres eliminar el proyecto poa: <b>{{ object.nombre_proyecto }}</b>?
  <br />
  <br />
  <button class="btn btn-danger" type="submit">BORRAR</button>
</form>
{% endblock %}

safet/templates/safet/reporteavances_confirm_delete.html
{% extends "base/base.html" %}
{% block titulo %}Borrar plan de actividades{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:consultar_reporte_avances' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Borrar plan de actividades</h1>
<form method="post">{% csrf_token %}
  ¿Está seguro que desea eliminar el plan de actividades de <b>{{ object.nombre_producto }}</b>?
  <br />
  <br />
  <button class="btn btn-danger" type="submit">BORRAR</button>
</form>
{% endblock %}

safet/templates/safet/reporteavances_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de planes de actividades de los productos{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'inicio:index' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de planes de actividades de los productos</h1>
{% if user.is_staff and user.is_active %}
<div class="glyphicon-white">
  <a href="{% url 'safet:consultar_reporte_avances_cv_por' %}" class="enlace_boton_panel">
    <div align="center">
    <i class="fa fa-line-chart"></i>
    Avance de los productos
    </div>
  </a>
</div>
{% endif %}
<br>
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th class="text-center">Nombre del producto</th>
      <th class="text-center">Tipo de producto</th>
      <th class="text-center">Cara visible</th>
      <th class="text-center">Año de ejecución</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td class="">{{ x.nombre_producto }}</td>
    <td class="text-center">{{ x.tipo_producto }}</td>
    <td class="">{{ x.nombre_caravisible }}</td>
    <td class="text-center">{{ x.ano_ejecucion }}</td>
    {% if user.is_superuser %}
      <td class="text-center td_botonera_tabla">
        <div class="row">
          <div class="col-sm-12">
            <a href="{% url 'safet:editar_reporte_avances' x.id %}" title="Editar">
              <i class="glyphicon glyphicon-pencil"></i>
            </a>
            <a href="{% url 'safet:detallar_reporte_avances' x.id %}" title="Detallar">
              <i class="glyphicon glyphicon-eye-open"></i>
            </a>
            <a href="{% url 'safet:borrar_reporte_avances' x.id %}" title="Borrar">
              <i class="glyphicon glyphicon-trash"></i>
            </a>
          </div>
        </div>
      </td>
    {% else %}
      {% if user.is_staff %}
        <td class="text-center td_botonera_tabla">
          <a href="{% url 'safet:detallar_reporte_avances' x.id %}" title="Detallar">
            <i class="glyphicon glyphicon-eye-open"></i>
          </a>
        </td>
      {% else %}
        {% if x.autor == user.username %}
          <td class="text-center td_botonera_tabla">
            <div class="row">
              <div class="col-sm-12">
                <a href="{% url 'safet:editar_reporte_avances_cv' x.id %}" title="Editar">
                  <i class="glyphicon glyphicon-pencil"></i>
                </a>
                <a href="{% url 'safet:detallar_reporte_avances' x.id %}" title="Detallar">
                  <i class="glyphicon glyphicon-eye-open"></i>
                </a>
              </div>
            </div>
          </td>
        {% else %}
          <td>&nbsp;</td>
        {% endif %}
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

safet/templates/safet/reporteavances_list_cv.html
{% extends "base/base.html" %}
{% block titulo %}Lista de planes de actividades de los productos{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'inicio:index' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de planes de actividades de los productos</h1>
<br />
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th class="text-center">Nombre del producto</th>
      <th class="text-center">Tipo de producto</th>
      <th class="text-center">Cara visible</th>
      <th class="text-center">Año de ejecución</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td class="">{{ x.nombre_producto }}</td>
    <td class="text-center">{{ x.tipo_producto }}</td>
    <td class="">{{ x.nombre_caravisible }}</td>
    <td class="text-center">{{ x.ano_ejecucion }}</td>
    {% if user.is_staff %}
      <td class="text-center td_botonera_tabla">
        <a href="{% url 'safet:detallar_reporte_avances' x.id %}" title="Detallar">
          <i class="glyphicon glyphicon-eye-open"></i>
        </a>
      </td>
    {% else %}
      {% if x.autor == user.username %}
        <td class="text-center td_botonera_tabla">
          <div class="row">
            <div class="col-sm-12">
              <a href="{% url 'safet:editar_reporte_avances_cv' x.id %}" title="Editar">
                <i class="glyphicon glyphicon-pencil"></i>
              </a>
              <a href="{% url 'safet:detallar_reporte_avances' x.id %}" title="Detallar">
                <i class="glyphicon glyphicon-eye-open"></i>
              </a>
            </div>
          </div>
        </td>
      {% else %}
        <td>&nbsp;</td>
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}