registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views
from registro.views import *
import registro.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    ##### Crud de los proyectos ######
    url(r'^consultar_proyecto$', login_required(views.Consultar_proyecto.as_view()), name='consultar_proyecto'),
    url(r'^registrar_proyecto$', login_required(views.Registrar_proyecto.as_view()), name='registrar_proyecto'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', login_required(views.Editar_proyecto.as_view()), name='editar_proyecto'),
    url(r'^borrar_proyecto/(?P<pk>\d+)$', login_required(views.Borrar_proyecto.as_view()), name='borrar_proyecto'),
    ##### Crud de los cara visibles ######
    url(r'^consultar_cara_visible$', login_required(views.Consultar_cara_visible.as_view()), name='consultar_cara_visible'),
    url(r'^registrar_cara_visible$', login_required(views.Registrar_cara_visible.as_view()), name='registrar_cara_visible'),
    url(r'^editar_cara_visible/(?P<pk>\d+)$', login_required(views.Editar_cara_visible.as_view()), name='editar_cara_visible'),
    url(r'^borrar_cara_visible/(?P<pk>\d+)$', login_required(views.Borrar_cara_visible.as_view()), name='borrar_cara_visible'),
    ##### Crud de los directores ######
    url(r'^consultar_director$', login_required(views.Consultar_director.as_view()), name='consultar_director'),
    url(r'^registrar_director$', login_required(views.Registrar_director.as_view()), name='registrar_director'),
    url(r'^editar_director/(?P<pk>\d+)$', login_required(views.Editar_director.as_view()), name='editar_director'),
    url(r'^borrar_director/(?P<pk>\d+)$', login_required(views.Borrar_director.as_view()), name='borrar_director'),
    ##### Crud de los cargos ######
    url(r'^consultar_cargo$', login_required(views.Consultar_cargo.as_view()), name='consultar_cargo'),
    url(r'^registrar_cargo$', login_required(views.Registrar_cargo.as_view()), name='registrar_cargo'),
    url(r'^editar_cargo/(?P<pk>\d+)$', login_required(views.Editar_cargo.as_view()), name='editar_cargo'),
    url(r'^borrar_cargo/(?P<pk>\d+)$', login_required(views.Borrar_cargo.as_view()), name='borrar_cargo'),
    ##### Crud de los reportes ######
    url(r'^consultar_reporte$', login_required(views.Consultar_reporte.as_view()), name='consultar_reporte'),
    url(r'^registrar_reporte$', login_required(views.Registrar_reporte.as_view()), name='registrar_reporte'),
    url(r'^editar_reporte/(?P<pk>\d+)$', login_required(views.Editar_reporte.as_view()), name='editar_reporte'),
    url(r'^editar_reporte_analista/(?P<pk>\d+)$', login_required(views.Editar_reporte_analista.as_view()), name='editar_reporte_analista'),
    url(r'^borrar_reporte/(?P<pk>\d+)$', login_required(views.Borrar_reporte.as_view()), name='borrar_reporte'),
    url(r'^detallar_reporte/(?P<pk>\d+)$', login_required(views.Detallar_reporte.as_view()), name='detallar_reporte'),
    ##### Filtros de búsqueda #####
    url(r'^buscar/$', login_required(views.Buscar_reporte.as_view()), name='buscar'),
    url(r'^busqueda/$', login_required(views.busqueda), name='busqueda'),
)

reporte_mensual_proyecto/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('inicio.urls', namespace='inicio')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^sisrep/', include('registro.urls', namespace='registro')),
    url(r'^safet/', include('safet.urls', namespace='safet')),
    url(r'^bitacora/', include('bitacora.urls', namespace='bitacora')),
    url(r'^admin/', include(admin.site.urls)),
]

safet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from safet import views
from safet.views import *
import safet.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^carga_inicial$', login_required(IndexCargaInicial.as_view()), name='inicio_carga_inicial'),
    url(r'^reporte_avances$', login_required(IndexReporte_avances.as_view()), name='inicio_reporte_avances'),
    url(r'^reporte_actividades$', login_required(IndexReporte_actividades.as_view()), name='inicio_reporte_actividades'),
    ##### Crud de los proyectos poa ######
    url(r'^consultar_proyecto$', login_required(views.Consultar_proyecto.as_view()), name='consultar_proyecto'),
    url(r'^registrar_proyecto$', login_required(views.Registrar_proyecto.as_view()), name='registrar_proyecto'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', login_required(views.Editar_proyecto.as_view()), name='editar_proyecto'),
    url(r'^borrar_proyecto/(?P<pk>\d+)$', login_required(views.Borrar_proyecto.as_view()), name='borrar_proyecto'),
    ##### Crud de las acciones específicas ######
    url(r'^consultar_accion$', login_required(views.Consultar_accion.as_view()), name='consultar_accion'),
    url(r'^registrar_accion$', login_required(views.Registrar_accion.as_view()), name='registrar_accion'),
    url(r'^editar_accion/(?P<pk>\d+)$', login_required(views.Editar_accion.as_view()), name='editar_accion'),
    url(r'^borrar_accion/(?P<pk>\d+)$', login_required(views.Borrar_accion.as_view()), name='borrar_accion'),
    ##### Crud de los Reportes de avances para los analistas ######
    url(r'^consultar_reporte_avances$', login_required(views.Consultar_reporte_avances.as_view()), name='consultar_reporte_avances'),
    url(r'^registrar_reporte_avances$', login_required(views.Registrar_reporte_avances.as_view()), name='registrar_reporte_avances'),
    url(r'^editar_reporte_avances/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances.as_view()), name='editar_reporte_avances'),
    url(r'^detallar_reporte_avances/(?P<pk>\d+)$', login_required(views.Detallar_reporte_avances.as_view()), name='detallar_reporte_avances'),
    url(r'^registrar_reporte_avances_software$', login_required(views.Registrar_reporte_avances_software.as_view()), name='registrar_reporte_avances_software'),
    url(r'^registrar_reporte_avances_cur_lin$', login_required(views.Registrar_reporte_avances_cur_lin.as_view()), name='registrar_reporte_avances_cur_lin'),
    url(r'^registrar_reporte_avances_jornada$', login_required(views.Registrar_reporte_avances_jornada.as_view()), name='registrar_reporte_avances_jornada'),
    url(r'^registrar_reporte_avances_publicacion$', login_required(views.Registrar_reporte_avances_publicacion.as_view()), name='registrar_reporte_avances_publicacion'),
    url(r'^borrar_reporte_avances/(?P<pk>\d+)$', login_required(views.Borrar_reporte_avances.as_view()), name='borrar_reporte_avances'),
    ##### Crud de los Reportes de Avances para los CV ######
    url(r'^consultar_reporte_avances_cv$', login_required(views.Consultar_reporte_avances_cv.as_view()), name='consultar_reporte_avances_cv'),
    url(r'^editar_reporte_avances_cv/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances_cv.as_view()), name='editar_reporte_avances_cv'),
    ##### Reportes porcentuales #####
    url(r'^buscar/$', login_required(views.Buscar.as_view()), name='consultar_reporte_avances_cv_por'),
    url(r'^busqueda/$', login_required(views.busqueda), name='busqueda'),
)

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from registro.models import Reporte, Proyecto, Caravisible, Director, Cargo
from bitacora.models import Bitacora
from forms import ReporteForm, ProyectoForm, CaravisibleForm, DirectorForm, CargoForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import *
from django.core.urlresolvers import *
from django.db.models import Count
from django.template import RequestContext
from django.contrib.auth.models import User
from django.shortcuts import redirect
from datetime import datetime
#is_superuser = Analista
#is_staff = Supervisor
#is_active = Cara visible


#################################
##### Crud de los productos #####
#################################

class Consultar_proyecto(ListView):
    """
    Clase que permite consultar la lista de Proyectos.
    """
    model = Proyecto

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario es admin para ver la lista de objetos.
        """
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            if (self.get_paginate_by(self.object_list) is not None
                    and hasattr(self.object_list, 'exists')):
                is_empty = not self.object_list.exists()
            else:
                is_empty = len(self.object_list) == 0
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.")
                        % {'class_name': self.__class__.__name__})
        context = self.get_context_data()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            messages_alert = ['No tiene permisos para listar los productos']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Registrar_proyecto(SuccessMessageMixin,CreateView):
    """
    Clase que permite registrar un producto.
    """
    model = Proyecto
    form_class = ProyectoForm
    success_url = reverse_lazy('registro:consultar_proyecto')
    success_message = "Se registro el producto con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario autenticado es admin
        para poder registrar un producto.
        """
        self.object = None
        if request.user.is_superuser:
            return super(Registrar_proyecto, self).get(request, *args, **kwargs)
        else:
            messages_alert = ['No tiene permisos para registrar un producto']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Editar_proyecto(SuccessMessageMixin,UpdateView):
    """
    Clase que permite editar la data guardada de un producto.
    """
    model = Proyecto
    form_class = ProyectoForm
    success_url = reverse_lazy('registro:consultar_proyecto')
    success_message = "Se actualizo el producto con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta editar el proyecto no es admin.
        """
        self.object = self.get_object()
        if request.user.is_superuser:
            return super(Editar_proyecto, self).get(request, *args, **kwargs)
        else:
            if str(self.object) == str(self.request.user):
                return super(Editar_proyecto, self).get(request, *args, **kwargs)
            else:
                messages_alert = ['No tiene permisos para editar el producto']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Borrar_proyecto(SuccessMessageMixin,DeleteView):
    """
    Clase que permite borrar un producto registrado.
    """
    model = Proyecto
    success_url = reverse_lazy('registro:consultar_proyecto')
    success_message = "Se elimino el producto con éxito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_proyecto, self).delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta borrar el proyecto no es admin.
        """
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        self.object = self.get_object()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            if str(self.object) == str(self.request.user):
                return self.render_to_response(context)
            else:
                messages_alert = ['No tiene permisos para borrar el producto']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


######################################
##### Crud de los caras visibles #####
######################################

class Consultar_cara_visible(ListView):
    """
    Clase que permite consultar la lista de caras visibles.
    """
    model = Caravisible

    def get(self, request, *args, **kwargs):
        """
        Método que valida si el usuario es admin para ver la lista de objetos.
        """
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            if (self.get_paginate_by(self.object_list) is not None
                    and hasattr(self.object_list, 'exists')):
                is_empty = not self.object_list.exists()
            else:
                is_empty = len(self.object_list) == 0
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.")
                        % {'class_name': self.__class__.__name__})
        context = self.get_context_data()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            messages_alert = ['No tiene permisos para listar los trabajadores']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Registrar_cara_visible(SuccessMessageMixin,CreateView):
    """
    Clase que permite registrar un cara visible en el sistema.
    """
    model = Caravisible
    form_class = CaravisibleForm
    success_url = reverse_lazy('registro:consultar_cara_visible')
    success_message = "Se registro el trabajador con éxito"

    def get(self, request, *args, **kwargs):
        """
        Méroto que valida si el usuario autenticado es admin
        para poder registrar un cara visible.
        """
        self.object = None
        if request.user.is_superuser:
            return super(Registrar_cara_visible, self).get(request, *args, **kwargs)
        else:
            messages_alert = ['No tiene permisos para registrar un cara visible']
            return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Editar_cara_visible(SuccessMessageMixin,UpdateView):
    """
    Clase que permite editar la data guardada de un cara visible.
    """
    model = Caravisible
    form_class = CaravisibleForm
    success_url = reverse_lazy('registro:consultar_cara_visible')
    success_message = "Se actualizo el trabajador con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta editar el cara visible no es admin.
        """
        self.object = self.get_object()
        if request.user.is_superuser:
            return super(Editar_cara_visible, self).get(request, *args, **kwargs)
        else:
            if str(self.object) == str(self.request.user):
                return super(Editar_cara_visible, self).get(request, *args, **kwargs)
            else:
                messages_alert = ['No tiene permisos para editar el cara visble']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Borrar_cara_visible(SuccessMessageMixin,DeleteView):
    """
    Clase que permite borrar un cara visible registrado en el sistema.
    """
    model = Caravisible
    success_url = reverse_lazy('registro:consultar_cara_visible')
    success_message = "Se elimino el trabajador con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a index si el usuario
        que intenta borrar el proyecto no es admin.
        """
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        self.object = self.get_object()
        if request.user.is_superuser:
            return self.render_to_response(context)
        else:
            if str(self.object) == str(self.request.user):
                return self.render_to_response(context)
            else:
                messages_alert = ['No tiene permisos para borrar el cara visible']
                return render_to_response("inicio/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_cara_visible, self).delete(request, *args, **kwargs)


##################################

registro/templates/registro/busqueda.html
{% extends "base/base.html" %}
{% block titulo %}Resultados de la búsqueda{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'registro:buscar' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Resultados de la búsqueda</h1>
<br />
{% if reportes %}
  <h4>Estas buscado reportes de tareas del año <strong>{{ query }}</strong> en el mes de <strong>{{ query2}}</strong></h4>
  <p>Reportes encontrados: <strong>{{ reportes|length }}</strong></p>
{% if user.is_superuser and user.is_staff and user.is_active %}
  <br />
  <a href="{% url 'registro:registrar_reporte' %}">
    <button class="btn btn-success">REGISTRAR</button>
  </a>
  <br>
  <br>
{% else %}
  {% if user.is_staff and user.is_active %}
  <br />
  {% else %}
    {% if user.is_active %}
      <br />
      <a href="{% url 'registro:registrar_reporte' %}">
        <button class="btn btn-success">REGISTRAR</button>
      </a>
      <br>
      <br>
    {% else %}
      xxx
    {% endif %}
  {% endif %}
{% endif %}
  <br />
  <table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
    <thead>
      <tr>
        <th class="text-center">N</th>
        <th class="text-center">Producto</th>
        <th class="text-center">Cara visible</th>
        <th class="text-center">Mes</th>
        <th class="text-center">Año</th>
        <th class="text-center">Registrado</th>
        {% if user.is_superuser and user.is_staff and user.is_active %}
          <th class="text-center">Estatus</th>
        {% endif %}
        <th class="text-center">Acciones</th>
      </tr>
    </thead>
    <tbody>
    {% for x in reportes %}
    <tr>
      <td class="text-center"></td>
      <td class="">{{ x.nombre_proyecto }}</td>
      <td class="">{{ x.nombre_caravisible }}</td>
      <td class="">{{ x.mes }}</td>
      <td class="text-center">{{ x.ano }}</td>
      <td class="">{{ x.fecha_registro_reporte }}</td>
      {% if user.is_superuser and user.is_staff and user.is_active %}
        {% if x.estatus == "act" %}
          <td class="text-center">Activo</td>
        {% elif x.estatus == "ina" %}
          <td class="text-center">Inactivo</td>
        {% else %}
        {% endif %}
      {% endif %}
      {% if request.user.is_superuser %}
      <td class="text-center td_botonera_tabla">
        <div class="row">
          <div class="col-sm-12">
            <a href="{% url 'registro:editar_reporte_analista' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
            <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
            <a href="{% url 'registro:borrar_reporte' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
          </div>
        </div>
      </td>
      {% else %}
        {% if x.autor == request.user.username %}
          <td class="text-center td_botonera_tabla">
            <div class="row">
              <div class="col-sm-12">
                <a href="{% url 'registro:editar_reporte' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
                <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
              </div>
            </div>
          </td>
        {% else %}
          {% if request.user.is_staff %}
            <td class="text-center td_botonera_tabla">
              <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
            </td>
          {% else %}
            <td></td>
          {% endif %}
        {% endif %}
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>Ningún reporte coincide con el criterio de búsqueda.</p>
  <br />
  <a href="{% url 'registro:buscar' %}"><button type="button" class="btn btn-primary">BUSCAR</button></a>
{% endif %}
{% endblock %}

registro/templates/registro/caravisible_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de trabajadores{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:inicio_carga_inicial' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de trabajadores</h1>
<br />
<a href="{% url 'registro:registrar_cara_visible' %}">
  <button class="btn btn-success">REGISTRAR</button>
</a>
<br />
<br />
<table border="1px" id="example" class="display">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th>Nombre del trabajador</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td>{{ x.nombre_caravisible }}</td>
    <td class="text-center td_botonera_tabla">
      <div class="row">
        <div class="col-sm-12">
          <a href="{% url 'registro:editar_cara_visible' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href="{% url 'registro:borrar_cara_visible' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
      </div>
    </td>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

registro/templates/registro/cargo_form.html
{% extends "base/base.html" %}
{% block titulo %}Registrar cargo{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'registro:consultar_cargo' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Registrar cargo</h1>
<br />
<div class="row">
  <div class="col-sm-6">
    <form method="post">{% csrf_token %}
      <div class="">
        <i class="fa fa-file-text-o color-blue-system"></i>
        <b>{{ form.nombre_cargo.label }}</b>
        <br />
        {{ form.nombre_cargo }}
        {% if form.nombre_cargo.errors %}
          <p>{{ form.nombre_cargo.errors}}</p>
        {% endif %}
      </div>
      <button class="btn btn-success" type="submit">REGISTRAR</button>
    </form>
  </div>
  <div class="col-sm-6"></div>
</div>
{% endblock %}

registro/templates/registro/cargo_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de cargos{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:inicio_carga_inicial' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a>Lista de cargos</h1>
<br />
<a href="{% url 'registro:registrar_cargo' %}">
  <button class="btn btn-success">REGISTRAR</button>
</a>
<br />
<br />
<table border="1px" id="example" class="display">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th>Nombre del cargo</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td>{{ x.nombre_cargo }}</td>
    <td class="text-center td_botonera_tabla">
      <div class="row">
        <div class="col-sm-12">
          <a href="{% url 'registro:editar_cargo' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href="{% url 'registro:borrar_cargo' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
      </div>
    </td>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

registro/templates/registro/proyecto_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de productos{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'safet:inicio_carga_inicial' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de productos</h1>
<br />
<a href="{% url 'registro:registrar_proyecto' %}">
  <button class="btn btn-success">REGISTRAR</button>
</a>
<br />
<br />
<table border="1px" id="example" class="display">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th>Nombre del producto</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td>{{ x.nombre_proyecto }}</td>
    <td class="text-center td_botonera_tabla">
      <div class="row">
        <div class="col-sm-12">
          <a href="{% url 'registro:editar_proyecto' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href="{% url 'registro:borrar_proyecto' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
      </div>
    </td>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

registro/templates/registro/tabla.html
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th class="text-center">Producto</th>
      <th class="text-center">Cara visible</th>
      <th class="text-center">Mes</th>
      <th class="text-center">Año</th>
      <th class="text-center">Registrado</th>
      {% if user.is_superuser and user.is_staff and user.is_active %}
        <th class="text-center">Estatus</th>
      {% endif %}
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td class="text-center"></td>
    <td class="text-center">{{ x.nombre_proyecto }}</td>
    <td class="text-center">{{ x.nombre_caravisible }}</td>
    <td class="text-center">{{ x.mes }}</td>
    <td class="text-center">{{ x.ano }}</td>
    <td class="text-center">{{ x.fecha_registro_reporte }}</td>
    {% if user.is_superuser and user.is_staff and user.is_active %}
      {% if x.estatus == "act" %}
        <td class="text-center">Activo</td>
      {% elif x.estatus == "ina" %}
        <td class="text-center">Inactivo</td>
      {% else %}
      {% endif %}
    {% endif %}
    {% if request.user.is_superuser %}
      <td class="text-center td_botonera_tabla">
        <div class="row">
          <div class="col-sm-12">
            <a href="{% url 'registro:editar_reporte_analista' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
            <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
            <a href="{% url 'registro:borrar_reporte' x.id %}" title="Borrar"><i class="glyphicon glyphicon-trash"></i></a>
          </div>
        </div>
      </td>
      {% else %}
      {% if x.autor == request.user.username %}
        <td class="text-center td_botonera_tabla">
          <div class="row">
            <div class="col-sm-12">
              {% if x.estatus == "act" %}
                <a href="{% url 'registro:editar_reporte' x.id %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
              {% endif %}
              <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
            </div>
          </div>
        </td>
      {% else %}
        {% if request.user.is_staff %}
          <td class="text-center td_botonera_tabla">
            <a href="{% url 'registro:detallar_reporte' x.id %}" title="Detallar"><i class="glyphicon glyphicon-eye-open"></i></a>
          </td>
        {% else %}
          <td></td>
        {% endif %}
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>