reporte_mensual_proyecto/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('inicio.urls', namespace='inicio')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^sisrep/', include('registro.urls', namespace='registro')),
    url(r'^safet/', include('safet.urls', namespace='safet')),
    url(r'^bitacora/', include('bitacora.urls', namespace='bitacora')),
    url(r'^admin/', include(admin.site.urls)),
]

safet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from safet import views
from safet.views import *
import safet.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^carga_inicial$', login_required(IndexCargaInicial.as_view()), name='inicio_carga_inicial'),
    url(r'^reporte_avances$', login_required(IndexReporte_avances.as_view()), name='inicio_reporte_avances'),
    url(r'^reporte_actividades$', login_required(IndexReporte_actividades.as_view()), name='inicio_reporte_actividades'),
    ##### Crud de los proyectos poa ######
    url(r'^consultar_proyecto$', login_required(views.Consultar_proyecto.as_view()), name='consultar_proyecto'),
    url(r'^registrar_proyecto$', login_required(views.Registrar_proyecto.as_view()), name='registrar_proyecto'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', login_required(views.Editar_proyecto.as_view()), name='editar_proyecto'),
    url(r'^borrar_proyecto/(?P<pk>\d+)$', login_required(views.Borrar_proyecto.as_view()), name='borrar_proyecto'),
    ##### Crud de las acciones específicas ######
    url(r'^consultar_accion$', login_required(views.Consultar_accion.as_view()), name='consultar_accion'),
    url(r'^registrar_accion$', login_required(views.Registrar_accion.as_view()), name='registrar_accion'),
    url(r'^editar_accion/(?P<pk>\d+)$', login_required(views.Editar_accion.as_view()), name='editar_accion'),
    url(r'^borrar_accion/(?P<pk>\d+)$', login_required(views.Borrar_accion.as_view()), name='borrar_accion'),
    ##### Crud de los Reportes de avances para los analistas ######
    url(r'^consultar_reporte_avances$', login_required(views.Consultar_reporte_avances.as_view()), name='consultar_reporte_avances'),
    url(r'^registrar_reporte_avances$', login_required(views.Registrar_reporte_avances.as_view()), name='registrar_reporte_avances'),
    url(r'^editar_reporte_avances/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances.as_view()), name='editar_reporte_avances'),
    url(r'^detallar_reporte_avances/(?P<pk>\d+)$', login_required(views.Detallar_reporte_avances.as_view()), name='detallar_reporte_avances'),
    url(r'^registrar_reporte_avances_software$', login_required(views.Registrar_reporte_avances_software.as_view()), name='registrar_reporte_avances_software'),
    url(r'^registrar_reporte_avances_cur_lin$', login_required(views.Registrar_reporte_avances_cur_lin.as_view()), name='registrar_reporte_avances_cur_lin'),
    url(r'^registrar_reporte_avances_jornada$', login_required(views.Registrar_reporte_avances_jornada.as_view()), name='registrar_reporte_avances_jornada'),
    url(r'^registrar_reporte_avances_publicacion$', login_required(views.Registrar_reporte_avances_publicacion.as_view()), name='registrar_reporte_avances_publicacion'),
    url(r'^borrar_reporte_avances/(?P<pk>\d+)$', login_required(views.Borrar_reporte_avances.as_view()), name='borrar_reporte_avances'),
    ##### Crud de los Reportes de Avances para los CV ######
    url(r'^consultar_reporte_avances_cv$', login_required(views.Consultar_reporte_avances_cv.as_view()), name='consultar_reporte_avances_cv'),
    url(r'^editar_reporte_avances_cv/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances_cv.as_view()), name='editar_reporte_avances_cv'),
    ##### Reportes porcentuales #####
    url(r'^buscar/$', login_required(views.Buscar.as_view()), name='consultar_reporte_avances_cv_por'),
    url(r'^busqueda/$', login_required(views.busqueda), name='busqueda'),
)

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <link rel="icon" href="{% static 'img/favicon-2021.png' %}">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/jquery-1.12.4.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <!-- DatePicker
    ================================================== -->
    <link rel="stylesheet" href="{% static 'datepicker/css/jquery-ui.css' %}?version=1.0 " type="text/css"/>
    <script src="{% static 'datepicker/jquery-ui.js' %}?version=1.0 " type="text/javascript"></script>
    <!-- DataTables JS
    ================================================== -->
    <script src="{% static 'datatables/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'datatables/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Select2
    ================================================== -->
    <script src="{% static 'select2/select2.min.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'select2/select2.min.css' %}">
    <!-- Scripts - js
    ================================================== -->
    <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
    <!-- Import CSS files -->
    <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/jquery.dataTables.min.css' %}">
    <!-- Import JS files -->
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/dataTables.buttons.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/buttons.flash.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/jszip.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/pdfmake.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/vfs_fonts.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/buttons.html5.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'datatables/js/buttons.print.min.js' %}"></script>
    <!-- Import pdfmake files -->
    <script src="{% static 'js/pdfmake.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/vfs_fonts.js' %}" type="text/javascript"></script>
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}?version=1.5" rel="stylesheet">
    <!-- Font-awesome CSS -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  </head>
<body>

<!-- Fixed navbar
================================================== -->
<nav class="navbar navbar-inverse navbar-fixed-top navbar-fixed-edit">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'inicio:index' %}">
      SISREP
    </a>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown dropdown-margin">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        {% if request.user.is_authenticated %}
          <i class="glyphicon glyphicon-user"></i>
          {% if user.is_superuser and user.is_staff and user.is_active %}
            {{ request.user.username }} (Analista) <span class="caret"></span>
          {% else %}
            {% if user.is_staff and user.is_active %}
              {{ request.user.username }} (Supervisor) <span class="caret"></span>
            {% else %}
              {% if user.is_active %}
                {{ request.user.username }} (Cara visible) <span class="caret"></span>
              {% else %}
                xxx
              {% endif %}
            {% endif %}
          {% endif %}
        {% endif %}
      </a>
      {% if request.user.is_authenticated %}
      <ul class="dropdown-menu">
        <li>
          <a href="{% url 'usuarios:change_password' %}">
            <i class="glyphicon glyphicon-wrench"></i>
            Cambiar contraseña
          </a>
        </li>
        <li>
          <a href="{% url 'usuarios:logout' %}">
            <i class="fa fa-sign-out"></i>
            Salir
          </a>
        </li>
      </ul>
      {% endif %}
    </li>
  </ul>
</nav>
<!-- Fixed navbar end -->

<!-- row class
================================================== -->
<div class="row">

  <!-- col-1
  ================================================== -->
  <div class="col-sm-1 left-column">
    <br />
    {% if request.user.is_authenticated %}
      <div class="text-center">
        <a href="{% url 'inicio:index' %}" data-toggle="tooltip" title="Inicio">
          <i class="fa fa-home color-white"></i>
        </a>
        <br />
        <br />
        <br />
        <!-- GESTIÓN DE USUARIOS -->
        {% if request.user.is_superuser %}
        <a href="{% url 'usuarios:list_users' %}" data-toggle="tooltip" title="Gestión de usuarios">
          <i class="fa fa-group color-white"></i>
        </a>
        <br />
        <br />
        <br />
        <!-- CARGA INICIAL -->
        <a href="{% url 'safet:inicio_carga_inicial' %}" data-toggle="tooltip" title="Carga inicial">
          <i class="fa fa-upload color-white"></i>
        </a>
        <br />
        <br />
        <br />
        {% else %}
        {% endif %}
        {% if request.user.is_superuser and request.user.is_staff and request.user.is_active %}
          <a href="{% url 'safet:consultar_reporte_avances' %}" data-toggle="tooltip" title="Actividades">
            <i class="fa fa-file-text color-white"></i>
          </a>
        {% else %}
          {% if request.user.is_staff and request.user.is_active %}
          <a href="{% url 'safet:consultar_reporte_avances' %}" data-toggle="tooltip" title="Actividades">
            <i class="fa fa-file-text color-white"></i>
          </a>
          {% else %}
            {% if request.user.is_active %}
              <a href="{% url 'safet:consultar_reporte_avances_cv' %}" data-toggle="tooltip" title="Actividades">
                <i class="fa fa-file-text color-white"></i>
              </a>
            {% endif %}
          {% endif %}
        {% endif %}
        <!-- TAREAS -->
        <!-- Analista -->
        {% if request.user.is_superuser and request.user.is_staff and request.user.is_active %}
          <br />
          <br />
          <br />
          <a href="{% url 'registro:buscar' %}" data-toggle="tooltip" title="Tareas">
            <i class="fa fa-tags color-white"></i>
          </a>
          {% else %}
            <!-- Supervisor -->
            {% if request.user.is_staff and request.user.is_active %}
              <br />
              <br />
              <br />
              <a href="{% url 'registro:buscar' %}" data-toggle="tooltip" title="Tareas">
                <i class="fa fa-tags color-white"></i>
              </a>
            {% else %}
            <!-- Cara visible -->
            {% if request.user.is_active %}
              <br />
              <br />
              <br />
              <a href="{% url 'registro:buscar' %}" data-toggle="tooltip" title="Tareas">
                <i class="fa fa-tags color-white"></i>
              </a>
            {% endif %}
          {% endif %}
        {% endif %}
        <!-- BITÁCORA DE EVENTOS -->
        {% if request.user.is_superuser %}
        <br />
        <br />
        <br />
        <a href="{% url 'bitacora:bitacora' %}" data-toggle="tooltip" title="Bitácora de eventos">
          <i class="fa fa-compass color-white"></i>
        </a>
        {% else %}
        {% endif %}
        <br />
        <br />
        <br />
        <a href="{% url 'usuarios:logout' %}" data-toggle="tooltip" title="Salir">
          <i class="fa fa-sign-out fa-sign-out-salir color-white"></i>
        </a>
      </div>
      {% else %}
        <div class="text-center">
        <a href="{% url 'inicio:index' %}" data-toggle="tooltip" title="Inicio">
          <i class="fa fa-home color-white"></i>
        </a>
        </div>
      {% endif %}
  </div>
  <!-- End col-1 -->

  <!-- col-11
  ================================================== -->
  <div class="col-sm-11 right-column">

    <!-- Container class
    ================================================== -->
    <div class="containerr container-all theme-showcase" role="main">

      <br />

      <!-- Well class
      ================================================== -->
      <div class="well-transparent">

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success alert-dismissable notificacion-emergente">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>
                  {% if message.tags %}{% endif %}
                  {{ message }}
                </strong>
            </div>
          {% endfor %}
        {% endif %}

        {% if messages_alert %}
          {% for message in messages_alert %}
            <div class="alert alert-danger alert-dismissable notificacion-emergente">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>
                  {% if message.tags %}{% endif %}
                  {{ message }}
                </strong>
            </div>
          {% endfor %}
        {% endif %}

        <div class="cuerpo">
        {% block cuerpo %}
        {% endblock %}
        </div>
      </div>
      <!-- End Well class -->

    </div>
    <!-- End Container class -->

  </div>
  <!-- End col-11 -->

</div>
<!-- End row class -->
</body>
</html>