reporte_mensual_proyecto/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('inicio.urls', namespace='inicio')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^sisrep/', include('registro.urls', namespace='registro')),
    url(r'^safet/', include('safet.urls', namespace='safet')),
    url(r'^bitacora/', include('bitacora.urls', namespace='bitacora')),
    url(r'^admin/', include(admin.site.urls)),
]

safet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from safet import views
from safet.views import *
import safet.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^carga_inicial$', login_required(IndexCargaInicial.as_view()), name='inicio_carga_inicial'),
    url(r'^reporte_avances$', login_required(IndexReporte_avances.as_view()), name='inicio_reporte_avances'),
    url(r'^reporte_actividades$', login_required(IndexReporte_actividades.as_view()), name='inicio_reporte_actividades'),
    ##### Crud de los proyectos poa ######
    url(r'^consultar_proyecto$', login_required(views.Consultar_proyecto.as_view()), name='consultar_proyecto'),
    url(r'^registrar_proyecto$', login_required(views.Registrar_proyecto.as_view()), name='registrar_proyecto'),
    url(r'^editar_proyecto/(?P<pk>\d+)$', login_required(views.Editar_proyecto.as_view()), name='editar_proyecto'),
    url(r'^borrar_proyecto/(?P<pk>\d+)$', login_required(views.Borrar_proyecto.as_view()), name='borrar_proyecto'),
    ##### Crud de las acciones específicas ######
    url(r'^consultar_accion$', login_required(views.Consultar_accion.as_view()), name='consultar_accion'),
    url(r'^registrar_accion$', login_required(views.Registrar_accion.as_view()), name='registrar_accion'),
    url(r'^editar_accion/(?P<pk>\d+)$', login_required(views.Editar_accion.as_view()), name='editar_accion'),
    url(r'^borrar_accion/(?P<pk>\d+)$', login_required(views.Borrar_accion.as_view()), name='borrar_accion'),
    ##### Crud de los Reportes de avances para los analistas ######
    url(r'^consultar_reporte_avances$', login_required(views.Consultar_reporte_avances.as_view()), name='consultar_reporte_avances'),
    url(r'^registrar_reporte_avances$', login_required(views.Registrar_reporte_avances.as_view()), name='registrar_reporte_avances'),
    url(r'^editar_reporte_avances/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances.as_view()), name='editar_reporte_avances'),
    url(r'^detallar_reporte_avances/(?P<pk>\d+)$', login_required(views.Detallar_reporte_avances.as_view()), name='detallar_reporte_avances'),
    url(r'^registrar_reporte_avances_software$', login_required(views.Registrar_reporte_avances_software.as_view()), name='registrar_reporte_avances_software'),
    url(r'^registrar_reporte_avances_cur_lin$', login_required(views.Registrar_reporte_avances_cur_lin.as_view()), name='registrar_reporte_avances_cur_lin'),
    url(r'^registrar_reporte_avances_jornada$', login_required(views.Registrar_reporte_avances_jornada.as_view()), name='registrar_reporte_avances_jornada'),
    url(r'^registrar_reporte_avances_publicacion$', login_required(views.Registrar_reporte_avances_publicacion.as_view()), name='registrar_reporte_avances_publicacion'),
    url(r'^borrar_reporte_avances/(?P<pk>\d+)$', login_required(views.Borrar_reporte_avances.as_view()), name='borrar_reporte_avances'),
    ##### Crud de los Reportes de Avances para los CV ######
    url(r'^consultar_reporte_avances_cv$', login_required(views.Consultar_reporte_avances_cv.as_view()), name='consultar_reporte_avances_cv'),
    url(r'^editar_reporte_avances_cv/(?P<pk>\d+)$', login_required(views.Editar_reporte_avances_cv.as_view()), name='editar_reporte_avances_cv'),
    ##### Reportes porcentuales #####
    url(r'^buscar/$', login_required(views.Buscar.as_view()), name='consultar_reporte_avances_cv_por'),
    url(r'^busqueda/$', login_required(views.busqueda), name='busqueda'),
)

usuarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from usuarios import views
from .views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

urlpatterns=patterns('',
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'logout/$',views.Logout.as_view(),name='logout'),
    url(r'^register$',views.RegisterUser.as_view(),name='register'),
    url(r'^list_users/$',login_required(views.ListUsers.as_view()),name='list_users'),
    url(r'^cambiar-contrasena/$',login_required(views.change_password),name='change_password'),
    url(r'^edit_user/(?P<pk>\d+)$',login_required(views.EditUser.as_view()),name='edit_user'),
    url(r'^delete_user/(?P<pk>\d+)$',login_required(views.DeleteUser.as_view()),name='delete_user'),
    url(r'^user_change_password/(?P<pk>\d+)$',login_required(views.user_change_password),name='user_change_password'),
    # Urls para el restablecimiento de contraseña por correo.
    url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect':'passwordsent/','template_name':'usuarios/password_reset_form.html',
        'email_template_name':'usuarios/password_reset_email.html'},name='password_reset'),
    url(r'^resetpassword/passwordsent/$','django.contrib.auth.views.password_reset_done',
        {'template_name':'usuarios/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect':reverse_lazy('usuarios:password_reset_complete'),'template_name':'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$','django.contrib.auth.views.password_reset_complete',
        {'template_name':'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),
)

usuarios/models.py
# -*- coding: utf-8 -*-

usuarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms import (
    ModelForm, TextInput, EmailInput, CharField, EmailField, PasswordInput, Select, CheckboxInput
)
from django import forms
from base.constantes import *


class LoginForm(AuthenticationForm):
    """
    Clase que gestiona los campos del formulario de
    inicio de sesión de usuarios del sistema.
    """
    username = forms.CharField(widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 15%; display: inline;',
    }), required = True)

    password = forms.CharField(widget=PasswordInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 15%; display: inline;',
    }), required = True)

    class Meta:
        model = User

    fields = [
        'username',
        'password',
    ]


class MyRegistrationForm(UserCreationForm):
    """
    Clase que gestiona el formulario para el registro de usuarios del sistema.
    """
    username = forms.CharField(label='Nombre de usuario',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '1'
    }), required = True)

    password1 = forms.CharField(label='Contraseña',widget=PasswordInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '5'
    }), required = True)

    password2 = forms.CharField(label='Confirmar contraseña',widget=PasswordInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '6'
    }), required = True)

    first_name = forms.CharField(label='Primer nombre',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '3'
    }), required = True)

    last_name = forms.CharField(label='Primer apellido',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '4'
    }), required = True)

    email = forms.EmailField(label='Correo electrónico',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '2'
    }), required = True)

    """
    is_active = forms.BooleanField(label='Cara visible',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)

    is_staff = forms.BooleanField(label='Director',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)

    is_superuser = forms.BooleanField(label='Analista',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)
    """
    rol = forms.ChoiceField(label='Rol', widget=Select(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices=usuarios,required=False)

    class Meta:
        model = User
        fields = ('username','password1','password2','first_name','last_name','email','rol')


class UserForm(forms.ModelForm):
    """
    Clase del formulario que permite actualizar la información de los usuarios del sistema.
    """
    username = forms.CharField(label='Nombre de usuario',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '1'
    }), required = True)

    first_name = forms.CharField(label='Primer nombre',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '3'
    }), required = True)

    last_name = forms.CharField(label='Primer apellido',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '4'
    }), required = True)

    email = forms.EmailField(label='Correo electrónico',widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'tabindex': '2'
    }), required = True)

    is_active = forms.BooleanField(label='Administrador',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)

    is_staff = forms.BooleanField(label='Analista de servicios',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)

    is_superuser = forms.BooleanField(label='Administrador',widget=CheckboxInput(attrs={
        'class':'checkbox',
    }), required = False)

    rol = forms.ChoiceField(label='Rol', widget=Select(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices=usuarios,required = False)

    class Meta:
        model = User
        exclude = ('password1','password2')
        fields = ('username','first_name','last_name','email','rol','is_active','is_staff','is_superuser')

usuarios/templates/usuarios/change_password.html
{% extends "base/base.html" %}
{% block titulo %}Cambiar contraseña{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{{ request.META.HTTP_REFERER }}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Cambiar contraseña</h1>
<br />
<form action="" method="post"> {% csrf_token %}
  <i class="fa fa-lock color-blue-system"></i>
  <label>Contraseña actual</label>
  <br />
  <br />
  {{ form.old_password }}
  {% if form.old_password.errors %}
    <p>{{ form.old_password.errors}}</p>
  {% endif %}
  <br />
  <br />
  <i class="fa fa-lock color-blue-system"></i>
  <label>Contraseña nueva</label>
  <br />
  {{ form.new_password1 }}
  {% if form.new_password1.errors %}
    <p>{{ form.new_password1.errors }}</p>
  {% endif %}
  <br />
  <br />
  <i class="fa fa-lock color-blue-system"></i>
  <label>Contraseña nueva (confirmación)</label>
  <br />
  {{ form.new_password2 }}
  {% if form.new_password2.errors %}
    <p>{{ form.new_password2.errors }}</p>
  {% endif %}
  <br />
  <br />
  <button class="btn btn-success" type="submit">CAMBIAR CONTRASEÑA</button>
</form>
{% endblock %}

usuarios/templates/usuarios/change_password_done.html
{% extends "base/base.html" %}
{% block titulo %}Cambio de contraseña exitoso{% endblock %}
{% block cuerpo %}
{% load staticfiles %}
<div align="center">
  <br />
  <br />
  <div align="center">
    <img class="img-lupa" src="{% static 'img/logo_sisrep.png' %}" width="20%">
  </div>
  <br />
  <br />
  <a href="{% url 'inicio:index' %}">
    <button class="btn btn-success" type="submit">
      INICIAR SESIÓN
    </button>
  </a>
</div>
{% endblock %}

usuarios/templates/usuarios/edit_user.html
{% extends "base/base.html" %}
{% block titulo %}Actualizar usuario{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'usuarios:list_users' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Actualizar usuario</h1>
<br />
<form action="" method="post">{% csrf_token %}
  <div class="row">
    <div class="col-sm-4">
      <i class="fa fa-user color-blue-system"></i>
      <label>{{ form.username.label }}</label>
      <br />
      {{ form.username }}
      {% if form.username.errors %}
        <br />
        <b>Alert: </b>{{ form.username.errors}}
      {% endif %}
      <br />
      <i class="fa fa-list-alt color-blue-system"></i>
      <label>{{ form.first_name.label }}</label>
      <br />
      {{ form.first_name }}
      {% if form.first_name.errors %}
        <br />
        <b>Alert: </b>{{ form.first_name.errors}}
      {% endif %}
      <br />
      <i class="fa fa-wpforms color-blue-system"></i>
      <label>{{ form.rol.label }}</label>
      <br />
      {% if form.is_active.value == True and form.is_staff.value == True and form.is_superuser.value == True %}
        <select class="form-control input-md form_style" id="id_rol" name="rol" style="min-width: 0; width: 100%; display: inline;">
          <option value="is_superuser">Analista</option>
          <option value="is_staff">Supervisor</option>
          <option value="is_active">Cara visible</option>
        </select>
      {% else %}
        {% if form.is_active.value == True and form.is_staff.value == True and form.is_superuser.value == False %}
          <select class="form-control input-md form_style" id="id_rol" name="rol" style="min-width: 0; width: 100%; display: inline;">
            <option value="is_staff">Supervisor</option>
            <option value="is_active">Cara visible</option>
            <option value="is_superuser">Analista</option>
          </select>
        {% else %}
          {% if form.is_active.value == True and form.is_staff.value == False and form.is_superuser.value == False %}
            <select class="form-control input-md form_style" id="id_rol" name="rol" style="min-width: 0; width: 100%; display: inline;">
              <option value="is_active">Cara visible</option>
              <option value="is_staff">Supervisor</option>
              <option value="is_superuser">Analista</option>
            </select>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
    <div class="col-sm-4">
      <i class="fa fa-envelope color-blue-system"></i>
      <label>{{ form.email.label }}</label>
      <br />
      {{ form.email }}
      {% if form.email.errors %}
        <br />
        <b>Alert: </b>{{ form.email.errors}}
      {% endif %}
      <br />
      <i class="fa fa-list-alt color-blue-system"></i>
      <label>{{ form.last_name.label }}</label>
      <br />
      {{ form.last_name }}
      {% if form.last_name.errors %}
        <br />
        <b>Alert: </b>{{ form.last_name.errors}}
      {% endif %}
    </div>
    <div class="col-sm-4">
    </div>
  </div>
  <button class="btn btn-success" type="submit">ACTUALIZAR</button>
  <a href="{% url 'usuarios:user_change_password' user.pk %}"><button type="button" class="btn btn-primary">CAMBIAR CONTRASEÑA</button>
</form>
{% endblock %}

usuarios/templates/usuarios/list_users.html
{% extends "base/base.html" %}
{% block titulo %}Lista de usuarios del sistema{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'inicio:index' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Lista de usuarios del sistema</h1>
<br />
<button class="btn btn-success" data-toggle="modal" data-target="#modal-registrar">REGISTRAR</button>
{% include 'usuarios/modals.html' %}
<br />
<br />
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">N</th>
      <th class="text-center">Nombre de usuario</th>
      <th class="text-center">Primer nombre</th>
      <th class="text-center">Primer apellido</th>
      <th class="text-center">Correo electrónico</th>
      <th class="text-center">Fecha de registro</th>
      <th class="text-center">Último acceso</th>
      <th class="text-center">Tipo</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for user in object_list %}
  <tr>
    <td class="text-center"></td>
    <td>{{ user.username }}</td>
    <td>{{ user.first_name }}</td>
    <td>{{ user.last_name }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.date_joined }}</td>
    <td>{{ user.last_login }}</td>
    {% if user.is_superuser == True and user.is_staff == True and user.is_active == True %}
      <td class="td_si">Analista</td>
    {% else %}
      {% if user.is_superuser == False and user.is_staff == True and user.is_active == True %}
        <td class="td_si">Supervisor</td>
      {% else %}
        {% if user.is_superuser == False and user.is_staff == False and user.is_active == True %}
          <td class="td_si">Cara visible</td>
        {% endif %}
      {% endif %}
    {% endif %}
    <td class="text-center td_botonera_tabla">
      <div class="row">
        <div class="col-sm-12">
          <a href="{% url 'usuarios:edit_user' user.pk %}" title="Editar"><i class="glyphicon glyphicon-pencil"></i></a>
          <a href="{{ user.id }}" title="Borrar" data-toggle="modal" data-target="#myModal{{user.id}}"><i class="glyphicon glyphicon-trash"></i></a>
          <div class="modal fade" id="myModal{{user.id}}" role="dialog">
            <div class="modal-dialog modal-md">
              <div class="modal-content">
                <div class="modal-body">
                  <form action="{% url 'usuarios:delete_user' user.id %}" method="post">{% csrf_token %}
                    <br>
                    <i class="fa fa-times-circle fa-lg"></i>
                    <br><br>
                    <h4>¿Estás seguro que quieres eliminar el usuario: <b>{{ user.username }}</b>?</h4>
                    <br>
                    <button type="button" class="btn btn-default" data-dismiss="modal">CANCELAR</button>
                    <button class="btn btn-danger" type="submit">BORRAR</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

usuarios/templates/usuarios/login.html
{% extends "base/base.html" %}
{% block titulo %}Iniciar sesión{% endblock %}
{% block cuerpo %}
{% load staticfiles %}
<div align="center">
  <img class="img-lupa" src="{% static 'img/logo_sisrep.png' %}" width="20%">
</div>
<div align="center">
  <form action="{% url 'usuarios:login' %}" method="post">{% csrf_token %}
    <br />
    <b>Usuario</b><br />
    <span class="glyphicon glyphicon-user color-blue-system"></span>
    {{ form.username }}
    <br />
    {% if form.username.errors %}
      <p>{{ form.username.errors}}</p>
    {% endif %}
    <b>Contraseña</b>
    <br />
    <span class="glyphicon glyphicon-lock color-blue-system"></span>
    {{ form.password }}
    <br />
    {% if form.password.errors %}
      <p>{{ form.password.errors}}</p>
    {% endif %}
    <button class="btn btn-success" type="submit">ENTRAR</button>
    <br>
    <br>
    <a class="enlace_boton_panel" href="{% url 'usuarios:password_reset' %}">¿Olvidó su contraseña?</a>
  </form>
  <br>
  <b>
    <a href="http://www.cenditel.gob.ve/" style="color:#343e48">
      Diseñado por Ing. Argenis Osorio, Desarrollado por CENDITEL.
    </a>
  </b>
</div>
{% endblock %}

usuarios/templates/usuarios/modals.html
<!-- Modal con el formulario de registro de usuarios-->
<div class="modal fade" id="modal-registrar" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Registrar usuario</h1>
      </div>
      <div class="modal-body">
        <form action="{% url 'usuarios:register' %}" method="post">{% csrf_token %}
          <div class="row">
            <div class="col-sm-6">
              <i class="fa fa-user color-blue-system"></i>
              <label>Nombre de usuario</label>
              <br />
              <input class="form-control input-md form_style" id="id_username" name="username" tabindex="1" type="text" required="required" />
              <i class="fa fa-list-alt color-blue-system"></i>
              <label>Primer nombre</label>
              <br />
              <input class="form-control input-md form_style" id="id_first_name" name="first_name" tabindex="3" type="text" required="required" />
              <i class="fa fa-lock color-blue-system"></i>
              <label>Contraseña</label>
              <br />
              <input class="form-control input-md form_style" id="id_password1" name="password1" tabindex="5" type="password" required="required" />
              <i class="fa fa-lock color-blue-system"></i>
              <label>Confirmar contraseña</label>
              <br />
              <input class="form-control input-md form_style" id="id_password2" name="password2" tabindex="6" type="password" required="required" />
            </div>
            <div class="col-sm-6">
              <i class="fa fa-envelope color-blue-system"></i>
              <label>Correo electrónico</label>
              <br />
              <input class="form-control input-md form_style" id="id_email" name="email" tabindex="2" type="email" required="required" />
              <i class="fa fa-list-alt color-blue-system"></i>
              <label>Primer apellido</label>
              <br />
              <input class="form-control input-md form_style" id="id_last_name" name="last_name" tabindex="4" type="text" required="required" />
              <i class="fa fa-wpforms color-blue-system"></i>
              <label>Rol</label>
              <br />
              <select class="form-control input-md form_style" id="id_rol" name="rol" required="required">
                <option value="is_active">Cara visible</option>
                <option value="is_staff">Supervisor</option>
                <option value="is_superuser">Analista</option>
              </select>
            </div>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">CANCELAR</button>
          <button class="btn btn-success" type="submit">REGISTRAR</button>
        </form>
      </div>
    </div>
  </div>
</div>

usuarios/templates/usuarios/password_reset_complete.html
{% extends "base/base.html" %}
{% load i18n %}
{% block titulo %}Contraseña restablecida{% endblock %}
{% block cuerpo %}
{% load staticfiles %}
<h4>Su contraseña ha sido restablecida. Ahora puede seguir adelante e <a href="{% url 'usuarios:login' %}">Iniciar sesión</a></h4>
{% endblock %}

usuarios/templates/usuarios/password_reset_done.html
{% extends "base/base.html" %}
{% load i18n %}
{% block titulo %}Restablecimiento de contraseña enviado{% endblock %}
{% block cuerpo %}
<br />
<h4>
  Le hemos enviado por correo electrónico las instrucciones para restablecer su contraseña, si es que existe un usuario en el sistema con la dirección electrónica que indicó, debería recibirlas en breve.
  <br />
  <br />
  Si no recibe un correo, por favor asegúrese que ha introducido la dirección de correo con la que se registró en el sistema y verifique su carpeta de spam.
</h4>
{% endblock %}

usuarios/templates/usuarios/password_reset_email.html
{% load i18n %}{% autoescape off %}
Recibes este correo electrónico porque has solicitado restablecer la contraseña para tu cuenta en {{ site_name }}.

Por favor, vaya a la página siguiente y escriba una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'usuarios:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Su nombre de usuario, en caso de haberlo olvidado es: {{ user.get_username }}
{% endautoescape %}

usuarios/templates/usuarios/register.html
{% extends "base/base.html" %}
{% block titulo %}Registrar usuario{% endblock %}
{% block cuerpo %}
<br />
<h1><a href="{% url 'usuarios:list_users' %}" class="regresar"><i class="fa fa-mail-reply fa-lg ollapsed"></i></a> Registrar usuario</h1>
<br />
<form action="{% url 'usuarios:register' %}" method="post">{% csrf_token %}
  <div class="row">
    <div class="col-sm-4">
      <i class="fa fa-user color-blue-system"></i>
      <label>{{ form.username.label }}</label>
      <br />
      {{ form.username }}
      {% if form.username.errors %}
        <br />
        <b>Alert: </b>{{ form.username.errors}}
      {% endif %}
      <br />
      <i class="fa fa-list-alt color-blue-system"></i>
      <label>{{ form.first_name.label }}</label>
      <br />
      {{ form.first_name }}
      {% if form.first_name.errors %}
        <br />
        <b>Alert: </b>{{ form.first_name.errors}}
      {% endif %}
      <br />
      <i class="fa fa-lock color-blue-system"></i>
      <label>{{ form.password1.label }}</label>
      <br />
      {{ form.password1 }}
      {% if form.password1.errors %}
        <br />
        <b>Alert: </b>{{ form.password1.errors}}
      {% endif %}
      <br />
      <i class="fa fa-lock color-blue-system"></i>
      <label>{{ form.password2.label }}</label>
      <br />
      {{ form.password2 }}
      {% if form.password2.errors %}
        <br />
        <b>Alert: </b>{{ form.password2.errors}}
      {% endif %}
    </div>
    <div class="col-sm-4">
      <i class="fa fa-envelope color-blue-system"></i>
      <label>{{ form.email.label }}</label>
      <br />
      {{ form.email }}
      {% if form.email.errors %}
        <br />
        <b>Alert: </b>{{ form.email.errors}}
      {% endif %}
      <br />
      <i class="fa fa-list-alt color-blue-system"></i>
      <label>{{ form.last_name.label }}</label>
      <br />
      {{ form.last_name }}
      {% if form.last_name.errors %}
        <br />
        <b>Alert: </b>{{ form.last_name.errors}}
      {% endif %}
      <br />
      <i class="fa fa-wpforms color-blue-system"></i>
      <label>{{ form.rol.label }}</label>
      <br />
      {{ form.rol }}
    </div>
    <div class="col-sm-4">
    </div>
  </div>
  <button class="btn btn-success" type="submit">REGISTRAR</button>
</form>
{% endblock %}